# Generated by Django 4.2.2 on 2025-05-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_available",
            field=models.BooleanField(
                default=False, verbose_name="Доступность в каталоге"
            ),
        ),
    ]
