# Generated by Django 5.2 on 2025-05-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0004_mymodel_alter_category_options_alter_product_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views_counter",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
